version: '3'

services:
  mysql:
    image: mysql:8.0.17
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: stats
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - "./mysql-data:/var/lib/mysql"